// <auto-generated />
using System;
using System.Collections.Generic;
using JobSuites.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobSuites.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928222222_SuiteFeatures")]
    partial class SuiteFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobSuites.Api.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("NextActionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_action_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_user_role");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.AssessmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnswerKey")
                        .HasColumnType("integer")
                        .HasColumnName("answer_key");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("domain");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<string>("WorkedSteps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("worked_steps");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "Difficulty")
                        .HasDatabaseName("ix_assessment_domain");

                    b.ToTable("assessment_items", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("availability");

                    b.Property<string>("BannerPicture")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("banner_picture");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("certifications");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("DesiredJobTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("desired_job_types")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("DesiredSalary")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("desired_salary");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("education");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Experiences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("experiences");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("headline");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Phone")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("phone");

                    b.Property<bool>("PhotoConsentGiven")
                        .HasColumnType("boolean")
                        .HasColumnName("photo_consent");

                    b.PrimitiveCollection<List<string>>("PreferredStates")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_states")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<List<string>>("TargetRoles")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("target_roles")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_profiles_content_hash");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_profiles_user");

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.InterviewPrep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("topics");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_prep_role");

                    b.ToTable("interview_preps", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.PrepAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HonestFramingUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("honest_framing_used");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_prep_answers_session_question");

                    b.ToTable("prep_answers", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.PrepSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mode");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scores");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_prep_sessions_user");

                    b.ToTable("prep_sessions", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("company");

                    b.PrimitiveCollection<List<string>>("ContactEmails")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("contact_emails");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExperienceRaw")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("experience_raw");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("JobType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int?>("MaxYears")
                        .HasColumnType("integer")
                        .HasColumnName("max_years");

                    b.Property<int?>("MinYears")
                        .HasColumnType("integer")
                        .HasColumnName("min_years");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<int>("PostingCount")
                        .HasColumnType("integer")
                        .HasColumnName("posting_count");

                    b.Property<string>("Qualification")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("qualification");

                    b.Property<string>("SalaryEstimate")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("salary_estimate");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.PrimitiveCollection<List<string>>("States")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("states");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Company", "Title")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_company_title");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.RoleMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.PrimitiveCollection<List<string>>("Gaps")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("gaps");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("ProfileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_hash");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ux_matches_user_role");

                    b.ToTable("role_matches", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.RolePosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_job_id");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_postings_role");

                    b.HasIndex("Source", "SourceJobId")
                        .IsUnique()
                        .HasDatabaseName("ux_postings_source_job");

                    b.ToTable("role_postings", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.SupportMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("SupportTicketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupportTicketId");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_messages_ticket");

                    b.ToTable("support_messages", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_tickets_user");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.TailoredDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coverage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("diff");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("document");

                    b.PrimitiveCollection<List<string>>("FactRefs")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fact_refs");

                    b.Property<string>("ProfileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("profile_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("verification");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_tailored_user_role_version");

                    b.ToTable("tailored_documents", (string)null);
                });

            modelBuilder.Entity("JobSuites.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobSuites.Api.Models.Application", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JobSuites.Api.Models.CandidateProfile", b =>
                {
                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithOne()
                        .HasForeignKey("JobSuites.Api.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSuites.Api.Models.InterviewPrep", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JobSuites.Api.Models.PrepAnswer", b =>
                {
                    b.HasOne("JobSuites.Api.Models.PrepSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("JobSuites.Api.Models.PrepSession", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JobSuites.Api.Models.RoleMatch", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobSuites.Api.Models.RolePosting", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Role")
                        .WithMany("Postings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JobSuites.Api.Models.SupportMessage", b =>
                {
                    b.HasOne("JobSuites.Api.Models.SupportTicket", null)
                        .WithMany("Messages")
                        .HasForeignKey("SupportTicketId");

                    b.HasOne("JobSuites.Api.Models.SupportTicket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("JobSuites.Api.Models.SupportTicket", b =>
                {
                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSuites.Api.Models.TailoredDocument", b =>
                {
                    b.HasOne("JobSuites.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSuites.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JobSuites.Api.Models.Role", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("JobSuites.Api.Models.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
